rest:
  template:
    domain: http://localhost:8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      client:
        registration:
          springauth:
            client-id: messaging-client
            client-secret: secret
            scope:
              - message.read
              - message.write
            authorizationGrantType: client_credentials
            provider: springauth
        provider:
          springauth:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
